### ISSUE TITLE
lzma: invalid option -- '0' for Debian on WSL

### ISSUE THREAD

**Issue by DGh0st** [theos/dm.pl#12]
What are the steps to reproduce this issue?
-------------------------------------------
1. Setup theos for Debian on WSL
2. Create a new empty project (error happens for any project)
3. Run `make clean package` (without FINALPACKAGE flag)

What happens?
-------------
![image](https://user-images.githubusercontent.com/13194700/52920585-b2c11f80-32d3-11e9-983c-ceabb9d8ba47.png)

What were you expecting to happen?
----------------------------------
There should be no error.

Any logs, error output, etc?
----------------------------
Image included above.

Any other comments?
-------------------
Commit [840b7e5](https://github.com/theos/theos/commit/840b7e5623b33702f841cf6679cb532a2f6c8200) is what introduced the issue.

It tries to set the compression level to 0 when FINALPACKAGE is not set which for some reason is invalid for Debian on WSL.

I tried the same configuration on Cygwin and there is no error (compress level of 0 is valid on Cygwin).

What versions of software are you using?
----------------------------------------
**Operating System:** Debian on WSL

**Toolchain Version:** One specified in WSL/linux installation guide

**SDK Version:** 8.1

**Comment by DGh0st** [comment]
That actually helped narrow down the root cause.

I have Debian 9.7 on WSL. So running `lzma --version` gives the following output:

```
LZMA command line tool 9.22
LZMA SDK 9.22
```

Which explains the error, it is using lzma comand line tool which doesn't support the `-0`. This is installed when you initially upgrade packages on debian, but uninstalling lzma fixes the issue since it would use xz-utils 5.2.2 instead.

**Comment by JeffResc** [comment]
After submitting [#379](https://github.com/theos/theos/issues/379), I can confirm these details on my case:
```
Jeffs-iPhone:~/ShortLook-Steam root# lzma --version
LZMA command line tool 4.32.7
LZMA SDK 4.32
```

Installing LZMA on my device won't work either as there are plenty of dependencies requiring it.

**Comment by DGh0st** [comment]
Uninstall lzma command lines tools using the package manager and then running `lzma --version` should print the following:

```
xz (XZ Utils) 5.2.2
liblzma 5.2.2
```
If it doesn't than you want to install xz utils which provides lzma compression (that supports `-0`).

**Comment by JeffResc** [comment]
[Heres the issue with removing LZMA](https://imgur.com/a/csOxtaG). Mainly looking at the essential packages like dpkg which are absolutely required.

**Comment by uroboro** [comment]
From https://linux.die.net/man/1/lzma (same for xz):

> Currently -0 is not very good (not much faster than -1 but much worse compression).

How about making https://github.com/theos/dm.pl/blob/master/dm.pl#L56-L58:

    if(($compression eq "bzip2" || $compression eq "gzip") && $compresslevel eq 0) {
    	$compresslevel = 1;
    }

be just `$compresslevel eq 0` and use `1` for compression level for all types?

**Comment by kirb** [comment]
Ah! Well, done in bb1278f.
